# Generated by Django 2.0.8 on 2018-09-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Contact_Number',
        ),
    ]
