# Generated by Django 2.0.8 on 2018-09-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_post_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Category',
            field=models.CharField(choices=[('dev', 'Developer'), ('rep', 'Reporter'), ('manager', 'Manager')], default='Developer', max_length=20),
        ),
    ]
